spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/panzhipiao
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver  # 数据库驱动类
        type: com.zaxxer.hikari.HikariDataSource  # 数据源类型

    # sql:
    #     init:
    #         schema-locations: classpath:sql/init.sql
    #         mode: always
